# -*- coding: utf-8 -*-
"""결막염_테스트용_코드.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otU-IIUun4diWixB3B6mfZCAtKcSiZ_E
"""

!pip install ultralytics

from ultralytics import YOLO
import json

model_path = '모델의 경로를 복붙하자'
img_path = '이미지의 경로를 복붙하자'
model = YOLO(model_path)
results = model(img_path)
for result in results:
  boxes = result.boxes.cpu().numpy()
box = boxes[0]
box_dict = {
    'cls': str(round(box.cls[0])), # 0 - 무증상, 1 - 결막염, 2 - 궤양성각막질환 , 3 - 백내장, 4 - 비궤양성각막질환, 5 - 색소침착성각막염, 6 - 안검내반증, 7 - 안검염, 8 - 안검종양, 9 - 유루증, 10 - 핵경화
    'conf': str(box.conf[0]), # json은 float을 변환 불가,
    'orig_shape': [box.orig_shape[0], box.orig_shape[1]], # [width, height]
    'xyxy': [round(v) for v in box.xyxy[0]], # [x시작좌표, y시작좌표, x종료좌표, y종료좌표]
}
json_str = json.dumps(box_dict, ensure_ascii=False, indent="\t")
print(json_str)
with open('/content' + '/' + 'json_file.json', "w", encoding="utf-8") as file_write: # 구글 코랩의 vm환경의 /content에 json파일을 만든다
    # write json data into file
    json.dump(box_dict, file_write, ensure_ascii=False, indent="\t") # 만든 json파일에 내용 적기, indent="\t" 있어야 한줄로 않나오고 탭넣어서 나옴